spring:
  application:
    name: ai-service

  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always

    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: mistral:latest
          num-ctx: 8192

      embedding:
        options:
          model: nomic-embed-text:latest

    vectorstore:
      pgvector:
        table-name: vector_store
        initialize-schema: true

  sql:
    init:
      mode: always
      schema-locations: classpath:init/schema.sql

rabbitmq:
  addresses: /Fittrack/ai-srvc/rabbitmq/addresses
  queue:
    activity-queue: activity_queue
    nutrition-queue: nutrition_queue
    user-queue: user_queue

aws:
  ssm:
    region: ap-south-1

  iam-user:
    accessKey: /Fittrack/accessKey
    secretKey: /Fittrack/secretKey

  postgres-db:
    url: /Fittrack/ai-srvc/postgres-db/url
    username: /Fittrack/ai-srvc/postgres-db/username
    password: /Fittrack/ai-srvc/postgres-db/password
    driver-class-name: org.postgresql.Driver

mongodb:
  uri: /Fittrack/ai-srvc/mongodb/uri
  database: /Fittrack/ai-srvc/mongodb/database

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8083